### ISSUE TITLE
[FEATURE] Individual Entry Preview

### ISSUE THREAD

**Issue by meisZWFLZ** [BattleCh1cken/notebookinator#32]
#### Requested Feature

I'd like to be able to render a specific entry on its own, without any of the frontmatter and appendix.

 - single entry
 - no frontmatter
 - no appendix

#### Current Implementation

You must include the following for the entry to actually render in the preview
```typst
#show notebook.with(/*...*/)
```

#### Motivation

This would make it easier to work on individual entries and quickly check that everything looks correct without any scrolling in the pdf preview.

#### (Optional) Possible Implementations and Alternatives

- open the pdf to a specific page but i couldn't figure out how to do this
- dont provide cover page -> radial theme creates a placeholder cover page

**Comment by BattleCh1cken** [comment]
I don't think its possible for us to support this. I considered having each `create_entry` function return content instead of modifying the global state of the template, however this created some issues that I didn't see a way to get around.
- Entries could be created out of order (ie you could have a frontmatter entry, a body entry, and then another frontmatter entry)
- We suddenly have no way of guaranteeing that the page count is correct at any point in the document

Even if it was possible this is too large of a refactor for the number of users it affects.

I know that my PDF viewer (Zathura) remembers which page it was viewing when the document reloads, so you may want to consider switching up your approach to viewing PDFs.
